-- ================================================================
-- Goa Tourism Intelligence Dashboard - Initial Schema
-- System 1: The Intelligence Agent Database
-- ================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ================================================================
-- TABLE 1: flight_prices
-- Real-time flight prices (populated by Amadeus API agent)
-- ================================================================
CREATE TABLE flight_prices (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  fetched_at TIMESTAMPTZ DEFAULT NOW(),

  -- Origin details
  origin_iata VARCHAR(10) NOT NULL,
  origin_city VARCHAR(100) NOT NULL,
  origin_country VARCHAR(100) NOT NULL,

  -- Destination details
  destination_iata VARCHAR(10) NOT NULL,
  destination_name VARCHAR(100) NOT NULL,

  -- Flight details
  departure_date DATE NOT NULL,
  return_date DATE,

  -- Pricing
  price_currency VARCHAR(3) DEFAULT 'EUR',
  price_amount DECIMAL(10,2),
  price_inr DECIMAL(10,2),

  -- Flight characteristics
  airline VARCHAR(100),
  direct_flight BOOLEAN DEFAULT false,
  cabin_class VARCHAR(20) DEFAULT 'ECONOMY',

  -- Metadata
  data_source VARCHAR(50) DEFAULT 'amadeus',
  raw_response JSONB,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for efficient querying
CREATE INDEX idx_flight_prices_route ON flight_prices(origin_iata, destination_iata, fetched_at DESC);
CREATE INDEX idx_flight_prices_date ON flight_prices(departure_date, fetched_at DESC);
CREATE INDEX idx_flight_prices_destination ON flight_prices(destination_iata, fetched_at DESC);

COMMENT ON TABLE flight_prices IS 'Real-time flight price data from Amadeus API for Goa vs competitor destinations';

-- ================================================================
-- TABLE 2: agent_analyses
-- Intelligence insights generated by the agent
-- ================================================================
CREATE TABLE agent_analyses (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Analysis metadata
  analysis_type VARCHAR(50) NOT NULL,
  -- Types: 'price_comparison', 'demand_signal', 'campaign_recommendation',
  --        'charter_opportunity', 'competitor_alert', 'market_trend'

  -- Content
  title VARCHAR(200) NOT NULL,
  summary TEXT NOT NULL,
  details JSONB NOT NULL,

  -- Classification
  severity VARCHAR(20) DEFAULT 'info', -- 'info', 'warning', 'critical', 'positive'
  source_market VARCHAR(100),

  -- Quality metrics
  confidence DECIMAL(3,2), -- 0.00 to 1.00
  actionable BOOLEAN DEFAULT false,
  recommended_action TEXT,

  -- Lifecycle
  expires_at TIMESTAMPTZ, -- when this analysis becomes stale

  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_agent_analyses_type ON agent_analyses(analysis_type, created_at DESC);
CREATE INDEX idx_agent_analyses_severity ON agent_analyses(severity, created_at DESC);
CREATE INDEX idx_agent_analyses_market ON agent_analyses(source_market, created_at DESC);

COMMENT ON TABLE agent_analyses IS 'AI-generated intelligence insights from the monitoring agent';

-- ================================================================
-- TABLE 3: arrival_stats
-- Verified arrival statistics (official government data only)
-- ================================================================
CREATE TABLE arrival_stats (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  recorded_at TIMESTAMPTZ DEFAULT NOW(),

  -- Period classification
  period_type VARCHAR(20) NOT NULL, -- 'annual', 'monthly', 'h1', 'q1', etc.
  period_label VARCHAR(50) NOT NULL, -- '2025', 'Jan 2025', 'H1 2025'
  year INTEGER NOT NULL,
  month INTEGER, -- null for annual/half-year/quarter

  -- Tourist counts
  domestic_tourists BIGINT,
  foreign_tourists BIGINT,
  total_tourists BIGINT,

  -- Charter operations
  charter_flights INTEGER,
  charter_tourists INTEGER,

  -- Scheduled international operations
  scheduled_intl_flights INTEGER,
  scheduled_intl_tourists INTEGER,

  -- Cruise operations
  cruise_vessels INTEGER,
  cruise_passengers_foreign INTEGER,
  cruise_passengers_domestic INTEGER,

  -- Data provenance
  data_source VARCHAR(200) NOT NULL, -- URL or reference
  data_release_date DATE, -- when govt published this
  is_provisional BOOLEAN DEFAULT false,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_arrival_stats_period ON arrival_stats(year, month);
CREATE INDEX idx_arrival_stats_type ON arrival_stats(period_type);

COMMENT ON TABLE arrival_stats IS 'Official government tourism arrival statistics for Goa';

-- ================================================================
-- TABLE 4: search_trends
-- Google Trends data for demand signals
-- ================================================================
CREATE TABLE search_trends (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  fetched_at TIMESTAMPTZ DEFAULT NOW(),

  -- Time period
  week_start DATE NOT NULL,

  -- Search query
  search_term VARCHAR(200) NOT NULL,

  -- Geography
  country_code VARCHAR(5) NOT NULL,
  country_name VARCHAR(100),

  -- Interest score
  interest_score INTEGER, -- 0-100 from Google Trends
  compared_to VARCHAR(200), -- what baseline term

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_search_trends_term ON search_trends(search_term, country_code, week_start DESC);
CREATE INDEX idx_search_trends_country ON search_trends(country_code, week_start DESC);

COMMENT ON TABLE search_trends IS 'Google Trends data for tourism demand signals';

-- ================================================================
-- TABLE 5: agent_runs
-- Agent execution log for monitoring and debugging
-- ================================================================
CREATE TABLE agent_runs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,

  -- Agent identification
  agent_type VARCHAR(50) NOT NULL, -- 'price_monitor', 'trend_analyzer', 'report_generator'

  -- Status tracking
  status VARCHAR(20) DEFAULT 'running', -- 'running', 'completed', 'failed', 'partial'

  -- Metrics
  routes_checked INTEGER,
  records_inserted INTEGER,
  analyses_generated INTEGER,

  -- Error handling
  error_message TEXT,

  -- Additional context
  metadata JSONB,

  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_agent_runs_type ON agent_runs(agent_type, started_at DESC);
CREATE INDEX idx_agent_runs_status ON agent_runs(status, started_at DESC);

COMMENT ON TABLE agent_runs IS 'Log of all agent executions for monitoring and debugging';

-- ================================================================
-- TABLE 6: competitor_stats
-- Monthly competitor destination data
-- ================================================================
CREATE TABLE competitor_stats (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Time period
  month DATE NOT NULL,

  -- Destination
  destination VARCHAR(100) NOT NULL, -- 'Bangkok', 'Phuket', 'Bali', 'Vietnam', 'Sri Lanka'
  destination_code VARCHAR(10), -- 'BKK', 'HKT', 'DPS', 'SGN', 'CMB'

  -- Arrival data
  total_international_arrivals BIGINT,
  arrivals_from_russia INTEGER,
  arrivals_from_uk INTEGER,
  arrivals_from_germany INTEGER,
  arrivals_from_israel INTEGER,
  arrivals_from_india INTEGER,

  -- Pricing data
  avg_hotel_price_3star_usd DECIMAL(10,2),
  avg_hotel_price_5star_usd DECIMAL(10,2),

  -- Data provenance
  source_url TEXT,
  data_release_date DATE,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_competitor_stats_destination ON competitor_stats(destination, month DESC);
CREATE INDEX idx_competitor_stats_month ON competitor_stats(month DESC);

COMMENT ON TABLE competitor_stats IS 'Monthly statistics for competitor destinations';

-- ================================================================
-- TABLE 7: forecasts
-- AI-generated arrival forecasts
-- ================================================================
CREATE TABLE forecasts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Forecast metadata
  forecast_date DATE NOT NULL, -- when forecast was generated
  target_month DATE NOT NULL, -- month being predicted

  -- Metric being forecasted
  metric VARCHAR(100) NOT NULL, -- 'total_foreign_arrivals', 'russian_arrivals', etc.

  -- Prediction values
  predicted_value DECIMAL(12,2),
  lower_bound DECIMAL(12,2), -- confidence interval lower
  upper_bound DECIMAL(12,2), -- confidence interval upper
  confidence DECIMAL(5,4), -- 0.0000 to 1.0000

  -- Model tracking
  model_version VARCHAR(50),
  model_type VARCHAR(50), -- 'prophet', 'sarima', 'lstm', etc.

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_forecasts_target ON forecasts(target_month, metric, forecast_date DESC);
CREATE INDEX idx_forecasts_date ON forecasts(forecast_date DESC);

COMMENT ON TABLE forecasts IS '90-day rolling arrival forecasts from predictive models';

-- ================================================================
-- TABLE 8: campaign_recommendations
-- AI-generated marketing campaign recommendations
-- ================================================================
CREATE TABLE campaign_recommendations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Target details
  target_market VARCHAR(100) NOT NULL,

  -- Timing
  recommended_start DATE,
  recommended_end DATE,

  -- Strategy
  channel VARCHAR(100), -- 'social', 'ota', 'charter_operator', 'search', etc.
  budget_allocation_pct DECIMAL(5,2),

  -- Rationale
  rationale TEXT,
  priority INTEGER, -- 1 (highest) to 10 (lowest)

  -- Lifecycle
  status VARCHAR(20) DEFAULT 'active', -- 'active', 'implemented', 'expired'

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_campaign_recommendations_market ON campaign_recommendations(target_market, created_at DESC);
CREATE INDEX idx_campaign_recommendations_priority ON campaign_recommendations(priority, status);

COMMENT ON TABLE campaign_recommendations IS 'AI-generated campaign timing and budget recommendations';

-- ================================================================
-- TABLE 9: intelligence_reports
-- Monthly auto-generated PDF reports
-- ================================================================
CREATE TABLE intelligence_reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Report period
  report_month DATE NOT NULL,

  -- Content
  title VARCHAR(200),
  executive_summary TEXT,
  full_report_json JSONB,

  -- Generated artifacts
  pdf_url TEXT,

  -- Generation metadata
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  generated_by VARCHAR(100), -- 'claude-api', 'manual', etc.

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_intelligence_reports_month ON intelligence_reports(report_month DESC);

COMMENT ON TABLE intelligence_reports IS 'Minister-ready monthly intelligence reports';

-- ================================================================
-- TABLE 10: hotel_prices
-- Daily hotel price comparisons
-- ================================================================
CREATE TABLE hotel_prices (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Date
  date DATE NOT NULL,

  -- Location
  destination VARCHAR(100) NOT NULL,
  destination_code VARCHAR(10),

  -- Category
  hotel_category VARCHAR(20) NOT NULL, -- '3-star', '4-star', '5-star', 'budget', 'luxury'

  -- Pricing
  avg_price_usd DECIMAL(10,2),
  avg_price_inr DECIMAL(10,2),
  min_price_usd DECIMAL(10,2),
  max_price_usd DECIMAL(10,2),

  -- Sample data
  sample_size INTEGER, -- how many hotels in the average

  -- Source
  source VARCHAR(50), -- 'booking.com', 'goibibo', 'manual'

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_hotel_prices_destination ON hotel_prices(destination, date DESC);
CREATE INDEX idx_hotel_prices_date ON hotel_prices(date DESC);

COMMENT ON TABLE hotel_prices IS 'Daily hotel pricing data for Goa vs competitor destinations';

-- ================================================================
-- VIEWS FOR COMMON QUERIES
-- ================================================================

-- Latest flight prices by route
CREATE VIEW v_latest_flight_prices AS
SELECT DISTINCT ON (origin_iata, destination_iata)
  origin_iata,
  origin_city,
  origin_country,
  destination_iata,
  destination_name,
  price_amount,
  price_currency,
  price_inr,
  airline,
  direct_flight,
  fetched_at
FROM flight_prices
ORDER BY origin_iata, destination_iata, fetched_at DESC;

-- Recovery progress vs 2017 benchmark
CREATE VIEW v_recovery_progress AS
SELECT
  period_label,
  year,
  month,
  foreign_tourists,
  domestic_tourists,
  total_tourists,
  charter_tourists,
  scheduled_intl_tourists,
  CASE
    WHEN year = 2017 THEN foreign_tourists
    ELSE NULL
  END as benchmark_2017,
  CASE
    WHEN year > 2017 THEN
      ROUND((foreign_tourists::DECIMAL /
        (SELECT foreign_tourists FROM arrival_stats WHERE year = 2017 AND period_type = 'annual')::DECIMAL) * 100, 2)
    ELSE NULL
  END as recovery_percentage
FROM arrival_stats
WHERE period_type IN ('annual', 'monthly')
ORDER BY year DESC, month DESC;

-- Latest analyses by severity
CREATE VIEW v_latest_analyses AS
SELECT
  analysis_type,
  title,
  summary,
  severity,
  source_market,
  confidence,
  actionable,
  recommended_action,
  created_at
FROM agent_analyses
WHERE expires_at IS NULL OR expires_at > NOW()
ORDER BY
  CASE severity
    WHEN 'critical' THEN 1
    WHEN 'warning' THEN 2
    WHEN 'positive' THEN 3
    WHEN 'info' THEN 4
  END,
  created_at DESC;

-- ================================================================
-- RLS (Row Level Security) Setup
-- Enable RLS on all tables (for future auth integration)
-- ================================================================

ALTER TABLE flight_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE arrival_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE search_trends ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitor_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE forecasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE intelligence_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE hotel_prices ENABLE ROW LEVEL SECURITY;

-- For now, allow all authenticated users to read (will refine later with roles)
CREATE POLICY "Allow read access to authenticated users" ON flight_prices FOR SELECT USING (true);
CREATE POLICY "Allow read access to authenticated users" ON agent_analyses FOR SELECT USING (true);
CREATE POLICY "Allow read access to authenticated users" ON arrival_stats FOR SELECT USING (true);
CREATE POLICY "Allow read access to authenticated users" ON search_trends FOR SELECT USING (true);
CREATE POLICY "Allow read access to authenticated users" ON agent_runs FOR SELECT USING (true);
CREATE POLICY "Allow read access to authenticated users" ON competitor_stats FOR SELECT USING (true);
CREATE POLICY "Allow read access to authenticated users" ON forecasts FOR SELECT USING (true);
CREATE POLICY "Allow read access to authenticated users" ON campaign_recommendations FOR SELECT USING (true);
CREATE POLICY "Allow read access to authenticated users" ON intelligence_reports FOR SELECT USING (true);
CREATE POLICY "Allow read access to authenticated users" ON hotel_prices FOR SELECT USING (true);

-- Allow service role to insert (for agents)
CREATE POLICY "Allow service role to insert" ON flight_prices FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role to insert" ON agent_analyses FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role to insert" ON arrival_stats FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role to insert" ON search_trends FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role to insert" ON agent_runs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role to insert" ON competitor_stats FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role to insert" ON forecasts FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role to insert" ON campaign_recommendations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role to insert" ON intelligence_reports FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role to insert" ON hotel_prices FOR INSERT WITH CHECK (true);

-- ================================================================
-- COMPLETE
-- ================================================================

COMMENT ON SCHEMA public IS 'Goa Tourism Intelligence Dashboard - System 1 (Intelligence Agent) Database';
